# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/heat_pump/ble/v1/thread_network_graph.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device/heat_pump/ble/v1/thread_network_graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2device/heat_pump/ble/v1/thread_network_graph.proto\x12\x17\x64\x65vice.heat_pump.ble.v1\")\n\x08NodePair\x12\r\n\x05\x66irst\x18\x01 \x01(\r\x12\x0e\n\x06second\x18\x02 \x01(\r\"W\n\x04\x45\x64ge\x12\x34\n\tnode_pair\x18\x01 \x01(\x0b\x32!.device.heat_pump.ble.v1.NodePair\x12\x0c\n\x04rssi\x18\x02 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"]\n\x04Node\x12\r\n\x05index\x18\x01 \x01(\r\x12/\n\x06\x64\x65vice\x18\x02 \x01(\x0e\x32\x1f.device.heat_pump.ble.v1.Device\x12\x15\n\rserial_number\x18\x03 \x01(\t\"p\n\x12ThreadNetworkGraph\x12,\n\x05nodes\x18\x01 \x03(\x0b\x32\x1d.device.heat_pump.ble.v1.Node\x12,\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x1d.device.heat_pump.ble.v1.Edge*s\n\x06\x44\x65vice\x12\x16\n\x12\x44\x45VICE_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x44\x45VICE_CONNECTIVITY_MANAGER\x10\x01\x12\x19\n\x15\x44\x45VICE_RANGE_EXTENDER\x10\x02\x12\x15\n\x11\x44\x45VICE_THERMOSTAT\x10\x03\x42\xad\x01\n\x17\x64\x65vice.heat_pump.ble.v1B\x17ThreadNetworkGraphProtoP\x01\xa2\x02\x03\x44HB\xaa\x02\x16\x44\x65vice.HeatPump.Ble.V1\xca\x02\x16\x44\x65vice\\HeatPump\\Ble\\V1\xe2\x02\"Device\\HeatPump\\Ble\\V1\\GPBMetadata\xea\x02\x19\x44\x65vice::HeatPump::Ble::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device.heat_pump.ble.v1.thread_network_graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027device.heat_pump.ble.v1B\027ThreadNetworkGraphProtoP\001\242\002\003DHB\252\002\026Device.HeatPump.Ble.V1\312\002\026Device\\HeatPump\\Ble\\V1\342\002\"Device\\HeatPump\\Ble\\V1\\GPBMetadata\352\002\031Device::HeatPump::Ble::V1'
  _globals['_DEVICE']._serialized_start=420
  _globals['_DEVICE']._serialized_end=535
  _globals['_NODEPAIR']._serialized_start=79
  _globals['_NODEPAIR']._serialized_end=120
  _globals['_EDGE']._serialized_start=122
  _globals['_EDGE']._serialized_end=209
  _globals['_NODE']._serialized_start=211
  _globals['_NODE']._serialized_end=304
  _globals['_THREADNETWORKGRAPH']._serialized_start=306
  _globals['_THREADNETWORKGRAPH']._serialized_end=418
# @@protoc_insertion_point(module_scope)