# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/heat_pump/command/v1/power_ct_clamp_setting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device/heat_pump/command/v1/power_ct_clamp_setting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8device/heat_pump/command/v1/power_ct_clamp_setting.proto\x12\x1b\x64\x65vice.heat_pump.command.v1\"\x81\x02\n\x18ThreePhaseCtClampSetting\x12K\n\x12port_1_orientation\x18\x01 \x01(\x0e\x32/.device.heat_pump.command.v1.CtClampOrientation\x12K\n\x12port_2_orientation\x18\x02 \x01(\x0e\x32/.device.heat_pump.command.v1.CtClampOrientation\x12K\n\x12port_3_orientation\x18\x03 \x01(\x0e\x32/.device.heat_pump.command.v1.CtClampOrientation\"a\n\x19SinglePhaseCtClampSetting\x12\x44\n\x0borientation\x18\x01 \x01(\x0e\x32/.device.heat_pump.command.v1.CtClampOrientation\"\xbd\x01\n\x13PowerCtClampSetting\x12N\n\x0csingle_phase\x18\x01 \x01(\x0b\x32\x36.device.heat_pump.command.v1.SinglePhaseCtClampSettingH\x00\x12L\n\x0bthree_phase\x18\x03 \x01(\x0b\x32\x35.device.heat_pump.command.v1.ThreePhaseCtClampSettingH\x00\x42\x08\n\x06group0*y\n\x12\x43tClampOrientation\x12$\n CT_CLAMP_ORIENTATION_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x43T_CLAMP_ORIENTATION_LEFT\x10\x01\x12\x1e\n\x1a\x43T_CLAMP_ORIENTATION_RIGHT\x10\x02\x42\xc2\x01\n\x1b\x64\x65vice.heat_pump.command.v1B\x18PowerCtClampSettingProtoP\x01\xa2\x02\x03\x44HC\xaa\x02\x1a\x44\x65vice.HeatPump.Command.V1\xca\x02\x1a\x44\x65vice\\HeatPump\\Command\\V1\xe2\x02&Device\\HeatPump\\Command\\V1\\GPBMetadata\xea\x02\x1d\x44\x65vice::HeatPump::Command::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device.heat_pump.command.v1.power_ct_clamp_setting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033device.heat_pump.command.v1B\030PowerCtClampSettingProtoP\001\242\002\003DHC\252\002\032Device.HeatPump.Command.V1\312\002\032Device\\HeatPump\\Command\\V1\342\002&Device\\HeatPump\\Command\\V1\\GPBMetadata\352\002\035Device::HeatPump::Command::V1'
  _globals['_CTCLAMPORIENTATION']._serialized_start=640
  _globals['_CTCLAMPORIENTATION']._serialized_end=761
  _globals['_THREEPHASECTCLAMPSETTING']._serialized_start=90
  _globals['_THREEPHASECTCLAMPSETTING']._serialized_end=347
  _globals['_SINGLEPHASECTCLAMPSETTING']._serialized_start=349
  _globals['_SINGLEPHASECTCLAMPSETTING']._serialized_end=446
  _globals['_POWERCTCLAMPSETTING']._serialized_start=449
  _globals['_POWERCTCLAMPSETTING']._serialized_end=638
# @@protoc_insertion_point(module_scope)