# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/heat_pump/command/v1/set_dhcp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device/heat_pump/command/v1/set_dhcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*device/heat_pump/command/v1/set_dhcp.proto\x12\x1b\x64\x65vice.heat_pump.command.v1\"\t\n\x07\x44hcpOff\"\x17\n\x06\x44hcpOn\x12\r\n\x05hours\x18\x01 \x01(\r\"\x85\x01\n\x07SetDhcp\x12\x38\n\x08\x64hcp_off\x18\x01 \x01(\x0b\x32$.device.heat_pump.command.v1.DhcpOffH\x00\x12\x36\n\x07\x64hcp_on\x18\x02 \x01(\x0b\x32#.device.heat_pump.command.v1.DhcpOnH\x00\x42\x08\n\x06group0B\xb6\x01\n\x1b\x64\x65vice.heat_pump.command.v1B\x0cSetDhcpProtoP\x01\xa2\x02\x03\x44HC\xaa\x02\x1a\x44\x65vice.HeatPump.Command.V1\xca\x02\x1a\x44\x65vice\\HeatPump\\Command\\V1\xe2\x02&Device\\HeatPump\\Command\\V1\\GPBMetadata\xea\x02\x1d\x44\x65vice::HeatPump::Command::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device.heat_pump.command.v1.set_dhcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033device.heat_pump.command.v1B\014SetDhcpProtoP\001\242\002\003DHC\252\002\032Device.HeatPump.Command.V1\312\002\032Device\\HeatPump\\Command\\V1\342\002&Device\\HeatPump\\Command\\V1\\GPBMetadata\352\002\035Device::HeatPump::Command::V1'
  _globals['_DHCPOFF']._serialized_start=75
  _globals['_DHCPOFF']._serialized_end=84
  _globals['_DHCPON']._serialized_start=86
  _globals['_DHCPON']._serialized_end=109
  _globals['_SETDHCP']._serialized_start=112
  _globals['_SETDHCP']._serialized_end=245
# @@protoc_insertion_point(module_scope)