# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device/heat_pump/command/v1/set_flow_meter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device/heat_pump/command/v1/set_flow_meter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0device/heat_pump/command/v1/set_flow_meter.proto\x12\x1b\x64\x65vice.heat_pump.command.v1\"\x9d\x04\n\x0cSetFlowMeter\x12G\n\nflow_meter\x18\x01 \x01(\x0e\x32\x33.device.heat_pump.command.v1.SetFlowMeter.FlowMeter\x12P\n\x0f\x66low_meter_type\x18\x02 \x01(\x0e\x32\x37.device.heat_pump.command.v1.SetFlowMeter.FlowMeterType\"\x8f\x02\n\rFlowMeterType\x12\x1f\n\x1b\x46LOW_METER_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x46LOW_METER_TYPE_DISABLED\x10\x01\x12$\n FLOW_METER_TYPE_HUBA_DN20_BRONZE\x10\x02\x12$\n FLOW_METER_TYPE_HUBA_DN25_BRONZE\x10\x03\x12%\n!FLOW_METER_TYPE_HUBA_DN20_PLASTIC\x10\x04\x12%\n!FLOW_METER_TYPE_HUBA_DN25_PLASTIC\x10\x05\x12%\n!FLOW_METER_TYPE_HUBA_DN10_PLASTIC\x10\x06\"`\n\tFlowMeter\x12\x1a\n\x16\x46LOW_METER_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x46LOW_METER_HEATING_SYSTEM\x10\x01\x12\x18\n\x14\x46LOW_METER_DHW_INLET\x10\x02\x42\xbb\x01\n\x1b\x64\x65vice.heat_pump.command.v1B\x11SetFlowMeterProtoP\x01\xa2\x02\x03\x44HC\xaa\x02\x1a\x44\x65vice.HeatPump.Command.V1\xca\x02\x1a\x44\x65vice\\HeatPump\\Command\\V1\xe2\x02&Device\\HeatPump\\Command\\V1\\GPBMetadata\xea\x02\x1d\x44\x65vice::HeatPump::Command::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device.heat_pump.command.v1.set_flow_meter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033device.heat_pump.command.v1B\021SetFlowMeterProtoP\001\242\002\003DHC\252\002\032Device.HeatPump.Command.V1\312\002\032Device\\HeatPump\\Command\\V1\342\002&Device\\HeatPump\\Command\\V1\\GPBMetadata\352\002\035Device::HeatPump::Command::V1'
  _globals['_SETFLOWMETER']._serialized_start=82
  _globals['_SETFLOWMETER']._serialized_end=623
  _globals['_SETFLOWMETER_FLOWMETERTYPE']._serialized_start=254
  _globals['_SETFLOWMETER_FLOWMETERTYPE']._serialized_end=525
  _globals['_SETFLOWMETER_FLOWMETER']._serialized_start=527
  _globals['_SETFLOWMETER_FLOWMETER']._serialized_end=623
# @@protoc_insertion_point(module_scope)